# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-StringTree
version:      0.03
version_from: lib/Template/Plugin/StringTree.pm
installdirs:  site
requires:
    Clone:                         0.14
    File::Spec:                    0.82
    List::Util:                    1.11
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
